import test from 'node:test';
import assert from 'node:assert/strict';
import { validateDeepAssuranceRequestV2 } from '../src/schema.mjs';
import { validateDeepAssuranceRequestWithV26V1 } from '../src/schema-v26.mjs';
import { enrichPhase6V26EvidenceV1 } from '../src/v26-execution-evidence-v1.mjs';

const baseRequest=()=>({schemaVersion:'deep-assurance-github-request-v2',processId:'audit-v7-independent-review',contractAutomationRelease:{repository:'CurveYield2/Contract-Automation',branch:'recovery/v7-execution-layer-v1',commit:'612fa50264e587e3f24550bf4dae35719b04211c',contractVersion:'contract-automation-v7-relocated-v1'},runnerRelease:{version:'deep-assurance-github-bridge-v1',manifestSha256:'2bebd99bb8ae770eb2feca0de7dc7e54596127a0c768922189e907e6658773dc'},campaignId:'campaign-1',assignmentId:'reviewer-2-phase-6-v1',phaseId:'build-and-test',gateId:'exact-build-and-tests-complete',profileId:'github-native-simulate-v2',source:{repository:'CurveYield2/Audits',commit:'1'.repeat(40),projectPath:'audit-targets/example'},configuration:{compilers:[{language:'solidity',version:'0.8.28'}],timeoutMinutes:20,analysis:{medusa:{version:'1.5.1'},nativeFuzz:{enabled:true,fuzzRuns:256}}},requestId:`dar-${'2'.repeat(32)}`,requestDigest:'3'.repeat(64)});

test('legacy v2 request remains byte-shape compatible through v26 wrapper',()=>{const request=baseRequest();assert.deepEqual(validateDeepAssuranceRequestWithV26V1(request),validateDeepAssuranceRequestV2(request));});

test('strict v26 extension is admitted without weakening legacy schema',()=>{const request=baseRequest();request.configuration.v26={phaseContractDigest:'4'.repeat(64),sbomRequired:true,phase6CampaignPlan:{sourceSnapshotDigest:'5'.repeat(64),harnessBundleDigest:'6'.repeat(64),requiredCampaignClasses:['property'],refinementRequired:false,deepEscalationRequired:false,activeCampaignClass:'property',runOrdinal:1,refinementOf:null,configurationDigest:'7'.repeat(64)},foundryCoverageObligations:[],foundryRefinementRequired:false,foundryRunType:'baseline',foundryRefinementOf:null,foundryBasisEvidenceIds:[]};const out=validateDeepAssuranceRequestWithV26V1(request);assert.equal(out.configuration.v26.sbomRequired,true);assert.throws(()=>validateDeepAssuranceRequestWithV26V1({...request,configuration:{...request.configuration,v26:{...request.configuration.v26,shell:'rm -rf /'}}}),/shell.*not allowed/i);});

test('phase6 enrichment emits source-bound campaign evidence and does not claim absent classes',async()=>{const request=baseRequest();request.configuration.v26={phaseContractDigest:'4'.repeat(64),sbomRequired:false,phase6CampaignPlan:{sourceSnapshotDigest:'5'.repeat(64),harnessBundleDigest:'6'.repeat(64),requiredCampaignClasses:['property','targeted'],refinementRequired:false,deepEscalationRequired:false,activeCampaignClass:'property',runOrdinal:1,refinementOf:null,configurationDigest:'7'.repeat(64)},foundryCoverageObligations:[],foundryRefinementRequired:false,foundryRunType:'baseline',foundryRefinementOf:null,foundryBasisEvidenceIds:[]};const result={status:'completed',build:{artifacts:[]},analysis:{medusa:{componentStatus:'COMPLETED',failureKind:null,campaign:{properties:[{name:'p',status:'passed'}],falsifiedProperties:0,corpus:{},coverage:{},statistics:{},metricAvailability:{corpus:'UNAVAILABLE_FROM_OUTPUT_MODE',coverage:'UNAVAILABLE_FROM_OUTPUT_MODE',statistics:'UNAVAILABLE_FROM_OUTPUT_MODE'}},rawArtifactRef:'github-actions://medusa'}}};const enriched=await enrichPhase6V26EvidenceV1({request,result,projectRoot:'/unused',mutableRpcRuntime:null});assert.equal(enriched.phase6CampaignEvidence.campaigns[0].campaignClass,'property');assert.equal(enriched.phase6CampaignEvidence.evaluation.status,'INCOMPLETE');assert.deepEqual(enriched.phase6CampaignEvidence.evaluation.missingCampaignClasses,['targeted']);assert.equal(enriched.phase6CampaignEvidence.campaigns[0].authoritativeFinding,false);});
