import {check,finalize,requireText,requireSha64,equalityCheck,nonEmptyArrayCheck} from './common-v1.mjs';

export function preflightCompileV1(c={}){
 const x=[];
 x.push(requireSha64('compile.snapshot',c.sourceSnapshotDigest,{code:'COMPILE_SOURCE_SNAPSHOT_MISSING',summary:'Compile source snapshot digest is missing',remediation:'Stage/hash the exact source before compile.'}));
 x.push(equalityCheck('compile.snapshot-binding',c.expectedSourceSnapshotDigest,c.sourceSnapshotDigest,{code:'COMPILE_SOURCE_SNAPSHOT_MISMATCH',summary:'Observed compile source snapshot differs from the expected staged source',remediation:'Discard the build workspace and restage the exact source before compilation.'}));
 x.push(requireText('compile.project-root',c.projectRoot,{code:'COMPILE_PROJECT_ROOT_MISSING',summary:'Compile project root is missing',remediation:'Use the exact detected project root.'}));
 x.push(check({id:'compile.project-root-exists',pass:c.projectRootExists===true,failureCode:'COMPILE_PROJECT_ROOT_NOT_FOUND',summary:'Compile project root does not exist',expected:true,observed:c.projectRootExists??null,remediation:'Fix source-staging/projectRoot before invoking compilers.'}));
 x.push(check({id:'compile.build-system',pass:['hardhat-native','foundry-native','solc-standard-json','mixed-native','vyper-native'].includes(c.buildSystem),failureCode:'COMPILE_BUILD_SYSTEM_UNSUPPORTED',summary:'Build system is unsupported or unresolved',expected:['hardhat-native','foundry-native','solc-standard-json','mixed-native','vyper-native'],observed:c.buildSystem??null,remediation:'Detect and select the admitted build path for this project.'}));
 x.push(check({id:'compile.build-manifest-root',pass:c.buildManifest?.status==='PASS',failureCode:'COMPILE_PROJECT_ROOT_BUILD_MANIFEST_MISSING',summary:'Selected project root is not the actual build root',expected:{status:'PASS',rootManifest:'root manifest or intentional standard-json root'},observed:c.buildManifest??null,remediation:'Use the dependency-complete project root that owns the detected build manifest; nested candidate manifests identify likely correct roots.'}));
 x.push(check({id:'compile.build-tool-probe',pass:c.buildToolProbe?.status==='PASS',failureCode:'COMPILE_BUILD_TOOL_PROBE_FAILURE',summary:'Actual build tool or locked build admission probe failed',expected:{status:'PASS'},observed:c.buildToolProbe??null,remediation:'Repair the exact build-tool version, package/lockfile state, or remapping command identified by this probe before compilation.'}));
 x.push(nonEmptyArrayCheck('compile.language-matrix',c.languages,{code:'COMPILE_LANGUAGE_MATRIX_EMPTY',summary:'Compiler/language matrix is empty',remediation:'Inventory Solidity/Vyper source languages before build.'}));
 const allowed=new Set(['solidity','vyper']);
 const unknown=(c.languages??[]).filter(l=>!allowed.has(l.language));
 x.push(check({id:'compile.languages-supported',pass:unknown.length===0,failureCode:'COMPILE_LANGUAGE_UNSUPPORTED',summary:'Source contains unsupported language entries',expected:['solidity','vyper'],observed:unknown,remediation:'Add an admitted compiler path or block the build explicitly.'}));
 const mism=(c.languages??[]).filter(l=>!l.requestedVersion||l.requestedVersion!==l.installedVersion);
 x.push(check({id:'compile.versions',pass:mism.length===0,failureCode:'COMPILE_COMPILER_VERSION_MISMATCH',summary:'Actual source compiler version differs from the requested compiler',expected:(c.languages??[]).map(l=>({language:l.language,version:l.requestedVersion})),observed:(c.languages??[]).map(l=>({language:l.language,version:l.installedVersion,probeStatus:l.probeStatus??null})),remediation:'Use the exact requested Solidity/Vyper compiler version before build.'}));
 x.push(equalityCheck('compile.settings',c.expectedCompilerSettingsDigest,c.observedCompilerSettingsDigest,{code:'COMPILE_SETTINGS_MISMATCH',summary:'Compiler settings, optimizer, EVM version, or via-IR configuration differs from expected',remediation:'Load the exact project/audit build settings; do not silently substitute optimizer, EVM, or via-IR settings.'}));
 x.push(check({id:'compile.import-graph',pass:c.importGraph?.status==='PASS',failureCode:'COMPILE_IMPORT_GRAPH_UNRESOLVED',summary:'Actual project import graph contains unresolved imports',expected:{status:'PASS',unresolvedImports:[]},observed:c.importGraph??null,remediation:'Use the dependency-complete project root and repair the exact missing dependency or remapping shown in unresolvedImports before compilation.',historicalSignatureId:'COMPILE-001'}));
 x.push(nonEmptyArrayCheck('compile.outputs',c.expectedArtifacts,{code:'COMPILE_EXPECTED_ARTIFACTS_UNDECLARED',summary:'Expected contract/artifact inventory is not declared',remediation:'Declare source:contract artifacts expected from this build.'}));
 x.push(check({id:'compile.expected-artifact-sources',pass:Array.isArray(c.missingArtifactSources)&&c.missingArtifactSources.length===0,failureCode:'COMPILE_EXPECTED_ARTIFACT_SOURCE_MISSING',summary:'One or more expected artifact source files are absent from the staged project',expected:[],observed:c.missingArtifactSources??null,remediation:'Correct the staged project root or expected artifact inventory before compilation.'}));
 return finalize('compile',c,x,{repository:c.repository,ref:c.ref,expectedOutputs:c.expectedArtifacts,rollback:'discard build workspace'});
}
