import {check,finalize,requireText,requireSha40} from './common-v1.mjs';
export function preflightFileMoveV1(c={}){
 const x=[],s=c.source??{},d=c.destination??{};
 for(const [id,v,code,sum,rem] of [['move.source.repository',s.repository,'MOVE_SOURCE_REPOSITORY_MISSING','Source repository is missing','Resolve exact source repository.'],['move.source.path',s.path,'MOVE_SOURCE_PATH_MISSING','Source path is missing','Resolve exact source path.'],['move.destination.path',d.path,'MOVE_DESTINATION_PATH_MISSING','Destination path is missing','Declare destination path.']]) x.push(requireText(id,v,{code,summary:sum,remediation:rem}));
 x.push(requireSha40('move.ref',s.ref,{code:'MOVE_SOURCE_REF_INVALID',summary:'Source move ref is not immutable',remediation:'Resolve the exact source commit.'}));
 x.push(requireSha40('move.blob',s.blobSha,{code:'MOVE_SOURCE_BLOB_INVALID',summary:'Source blob SHA is missing',remediation:'Read source blob SHA; same-repository move must reuse it.'}));
 x.push(check({id:'move.same-repository',pass:s.repository===d.repository&&s.ref===d.ref,failureCode:'MOVE_NOT_SAME_REPOSITORY_REF',summary:'file-move is only for a same-repository/ref rename',expected:{repository:s.repository,ref:s.ref},observed:{repository:d.repository,ref:d.ref},remediation:'Use file-transfer for cross-repository/ref copies.'}));
 x.push(check({id:'move.blob-reuse',pass:c.transferMethod==='GIT_TREE_REUSE_BLOB'&&c.expectedTransferredBytes===0,failureCode:'MOVE_BLOB_REUSE_REQUIRED',summary:'Same-repository move would re-upload bytes instead of reusing the blob',expected:{transferMethod:'GIT_TREE_REUSE_BLOB',expectedTransferredBytes:0},observed:{transferMethod:c.transferMethod??null,expectedTransferredBytes:c.expectedTransferredBytes??null},remediation:'Create one tree referencing the existing source blob at destination and deleting source.'}));
 x.push(check({id:'move.overwrite',pass:d.exists!==true||c.overwriteIntent===true,failureCode:'MOVE_DESTINATION_EXISTS',summary:'Destination exists without explicit overwrite intent',expected:true,observed:{exists:d.exists??null,overwriteIntent:c.overwriteIntent??false},remediation:'Resolve destination conflict before the tree mutation.'}));
 x.push(check({id:'move.verify',pass:c.verifyDestinationBlob===true,failureCode:'MOVE_POSTVERIFY_MISSING',summary:'Destination blob verification is not planned',expected:true,observed:c.verifyDestinationBlob??null,remediation:'Verify destination blob SHA equals original source blob SHA.'}));
 x.push(requireText('move.rollback',c.rollbackPlan,{code:'MOVE_ROLLBACK_MISSING',summary:'Move rollback plan is missing',remediation:'Record prior tree/commit so the move can be reverted atomically.'}));
 return finalize('file-move',c,x,{repository:s.repository,ref:s.ref,expectedOutputs:[d.path].filter(Boolean),rollback:c.rollbackPlan});
}
