import {check,finalize,requireSha64,equalityCheck} from './common-v1.mjs';
export function preflightFoundryV1(c={}){
 const x=[];
 if(c.medusaPredecessorRequired===true)x.push(check({id:'foundry.medusa-order',pass:['COMPLETED','COMPLETED_WITH_FAILURES','FAILED','PROPERTY_FALSIFICATION','NO_TESTS_DISCOVERED'].includes(c.medusaTerminalStatus),failureCode:'FOUNDRY_MEDUSA_PREDECESSOR_NOT_TERMINAL',summary:'Foundry started before required Medusa terminal evidence',expected:'terminal Medusa disposition',observed:c.medusaTerminalStatus??null,remediation:'Finish/record the required Medusa campaign first.'}));
 x.push(equalityCheck('foundry.version','1.7.1',c.observedVersion,{code:'FOUNDRY_VERSION_MISMATCH',summary:'Forge version is not canonical',remediation:'Use pinned Forge 1.7.1.'}));
 x.push(requireSha64('foundry.source-snapshot',c.sourceSnapshotDigest,{code:'FOUNDRY_SOURCE_SNAPSHOT_MISSING',summary:'Foundry source snapshot digest is missing',remediation:'Bind Foundry to the exact staged source.'}));
 x.push(equalityCheck('foundry.source-bind',c.expectedSourceSnapshotDigest,c.sourceSnapshotDigest,{code:'FOUNDRY_STALE_SNAPSHOT',summary:'Foundry snapshot differs from the frozen predecessor/source state',remediation:'Use the same immutable staged snapshot; do not restage/recheckout.'}));
 x.push(check({id:'foundry.compile',pass:c.compileProbe?.status==='PASS',failureCode:'FOUNDRY_COMPILE_PROBE_FAILED',summary:'Actual Foundry overlay does not compile/list tests cleanly',expected:'PASS',observed:c.compileProbe??null,remediation:'Repair audit-only test/overlay compilation before fuzz/invariant execution.'}));
 x.push(check({id:'foundry.tests',pass:Number.isInteger(c.discoveredTestCount)&&c.discoveredTestCount>0,failureCode:'FOUNDRY_NO_TESTS_DISCOVERED',summary:'No Foundry tests were discovered for the requested campaign',expected:'>0',observed:{count:c.discoveredTestCount??null,names:c.discoveredTests??[]},remediation:'Fix test selectors/naming/project root before running fuzz.',historicalSignatureId:'FOUNDRY-NOTESTS-001'}));
 if(c.invariantRequired===true)x.push(check({id:'foundry.handlers',pass:Number.isInteger(c.discoveredHandlerCount)&&c.discoveredHandlerCount>0,failureCode:'FOUNDRY_INVARIANT_HANDLER_MISSING',summary:'Invariant campaign has no discovered invariant/handler surface',expected:'>0',observed:c.discoveredHandlerCount??null,remediation:'Configure target contract/selectors/handlers before invariant execution.'}));
 if(c.forkRequired===true)x.push(check({id:'foundry.fork',pass:c.rpcProbe?.chainId===1&&c.rpcProbe?.blockHash===c.expectedBlockHash,failureCode:'FOUNDRY_FORK_IDENTITY_MISMATCH',summary:'Foundry fork identity is not the frozen Ethereum block',expected:{chainId:1,blockHash:c.expectedBlockHash},observed:c.rpcProbe??null,remediation:'Use the same normalized RPC/frozen block as Medusa/source evidence.'}));
 if(c.semanticSmokeStatus!==undefined)x.push(check({id:'foundry.semantic-result',pass:c.semanticSmokeStatus==='PASS',failureCode:'FOUNDRY_SEMANTIC_SUITE_FAILURE',summary:'Forge smoke reported failed tests or a non-success terminal suite even though process exit status may be zero',expected:'PASS semantic suite result',observed:{semanticSmokeStatus:c.semanticSmokeStatus,raw:c.semanticSmokeRaw??null},remediation:'Inspect the exact failing test/revert in the bounded target smoke and repair the harness/target/config before the full fuzz campaign.',historicalSignatureId:'FOUNDRY-001'}));
 x.push(check({id:'foundry.secret-redaction',pass:c.normalizedEvidenceContainsRpcSecret!==true,failureCode:'FOUNDRY_SECRET_LEAK_IN_EVIDENCE',summary:'Normalized Foundry preflight evidence contains RPC secret material',expected:false,observed:c.normalizedEvidenceContainsRpcSecret??false,remediation:'Redact runtime RPC URLs/secrets from stdout, stderr, command evidence and receipts.'}));
 x.push(check({id:'foundry.coverage-obligations',pass:c.coverageObligationsValid===true,failureCode:'FOUNDRY_COVERAGE_OBLIGATION_INVALID',summary:'Coverage obligations are not machine-readable/valid',expected:true,observed:c.coverageErrors??c.coverageObligationsValid??null,remediation:'Fix coverage obligation schema before execution.'}));
 x.push(check({id:'foundry.output-paths',pass:c.outputPathsWritable===true,failureCode:'FOUNDRY_EVIDENCE_PATH_NOT_WRITABLE',summary:'Raw/coverage evidence destinations are not writable',expected:true,observed:c.outputPathsWritable??null,remediation:'Create/verify bounded evidence directories before running Forge.'}));
 return finalize('foundry',c,x,{repository:c.repository,ref:c.ref,expectedOutputs:c.expectedOutputs,rollback:'terminate fuzz process and discard workspace'});
}
