import {check,finalize,requireSha64,equalityCheck} from './common-v1.mjs';
const TERMINAL=new Set(['COMPLETED','COMPLETED_WITH_FAILURES','FAILED','PROPERTY_FALSIFICATION','NO_TESTS_DISCOVERED']);
export function preflightMedusaV1(c={}){
 const x=[];
 x.push(equalityCheck('medusa.version','1.5.1',c.observedVersion,{code:'MEDUSA_VERSION_MISMATCH',summary:'Medusa version is not canonical',remediation:'Use pinned Medusa 1.5.1.',history:'MEDUSA-TOOL-001'}));
 x.push(requireSha64('medusa.source-snapshot',c.sourceSnapshotDigest,{code:'MEDUSA_SOURCE_SNAPSHOT_MISSING',summary:'Source snapshot digest is missing',remediation:'Stage and hash the exact project before Medusa.'}));
 x.push(equalityCheck('medusa.source-bind',c.expectedSourceSnapshotDigest,c.sourceSnapshotDigest,{code:'MEDUSA_SOURCE_SNAPSHOT_MISMATCH',summary:'Medusa staged source differs from request binding',remediation:'Discard stale stage and rematerialize exact source once.'}));
 x.push(requireSha64('medusa.harness-digest',c.harnessBundleDigest,{code:'MEDUSA_HARNESS_DIGEST_MISSING',summary:'Harness bundle digest is missing',remediation:'Validate the exact auditor-authored harness overlay.'}));
 x.push(equalityCheck('medusa.harness-bind',c.expectedHarnessBundleDigest,c.harnessBundleDigest,{code:'MEDUSA_HARNESS_DIGEST_MISMATCH',summary:'Medusa harness differs from request binding',remediation:'Use the exact approved overlay; do not modify production source.'}));
 x.push(check({id:'medusa.crytic-compile',pass:c.cryticCompileProbe?.status==='PASS',failureCode:'MEDUSA_CRYTIC_COMPILE_FAILURE',summary:'crytic-compile cannot consume the actual staged project view',expected:'PASS',observed:c.cryticCompileProbe??null,remediation:'Run the actual project through crytic-compile preflight and repair build-view incompatibility before fuzzing.',historicalSignatureId:c.cryticCompileProbe?.error?.includes?.('sourceMap')?'MEDUSA-006':'MEDUSA-CRYTIC-001'}));
 if(c.hasVyper===true)x.push(check({id:'medusa.mixed-language',pass:c.mixedLanguageProbe?.status==='PASS',failureCode:'MEDUSA_MIXED_LANGUAGE_BUILDINFO_FAILURE',summary:'Mixed Solidity/Vyper project view is not safe for Medusa/crytic-compile',expected:'PASS with explicit Vyper isolation when required',observed:c.mixedLanguageProbe??null,remediation:'Compile Vyper separately and exclude exact incompatible Vyper sources from the Medusa Foundry build-info view.',historicalSignatureId:'MEDUSA-006'}));
 if(c.propertiesRequired===true){x.push(check({id:'medusa.property-testing',pass:c.propertyTestingEnabled===true,failureCode:'MEDUSA_PROPERTY_TESTING_DISABLED',summary:'Property testing is disabled although property/invariant evidence is required',expected:true,observed:c.propertyTestingEnabled??null,remediation:'Set propertyTesting.enabled=true in the actual Medusa overlay.',historicalSignatureId:'MEDUSA-003'}));x.push(check({id:'medusa.stop-no-tests',pass:c.stopOnNoTests===true,failureCode:'MEDUSA_STOP_ON_NO_TESTS_DISABLED',summary:'Medusa is not fail-closed when no properties are discovered',expected:true,observed:c.stopOnNoTests??null,remediation:'Set stopOnNoTests=true so a no-tests campaign cannot masquerade as success.',historicalSignatureId:'MEDUSA-004'}));x.push(check({id:'medusa.property-discovery',pass:Number.isInteger(c.discoveredPropertyCount)&&c.discoveredPropertyCount>0,failureCode:'MEDUSA_NO_PROPERTIES',summary:'The actual staged harness exposes zero Medusa properties/invariants',expected:'>0 discovered properties',observed:{count:c.discoveredPropertyCount??null,names:c.discoveredProperties??[]},remediation:'Fix harness/config/property prefixes before running the expensive campaign.',historicalSignatureId:'MEDUSA-004'}));}
 x.push(check({id:'medusa.coverage-mode',pass:c.coverageProbe?.status==='PASS',failureCode:'MEDUSA_COVERAGE_MODE_FAILURE',summary:'Configured coverage mode triggers a known Medusa no-tests/coverage crash',expected:'PASS',observed:c.coverageProbe??null,remediation:'Use a coverage configuration proven not to hit the empty/disabled coverage tracer failure.',historicalSignatureId:'MEDUSA-005'}));
 const parser=c.parserProbe??{}, parserPass=['pass','falsification','noTests','unicodePrefix'].every(k=>parser[k]===true);
 x.push(check({id:'medusa.output-parser',pass:parserPass,failureCode:'MEDUSA_TERMINAL_OUTPUT_PARSER_INCOMPATIBLE',summary:'Runner parser cannot normalize all required real Medusa 1.5.1 terminal output forms',expected:{pass:true,falsification:true,noTests:true,unicodePrefix:true},observed:parser,remediation:'Run parser probes against actual Medusa stdout/stderr framing before campaign execution.',historicalSignatureId:parser.unicodePrefix===false?'MEDUSA-002':'MEDUSA-001'}));
 if(c.forkRequired===true)x.push(check({id:'medusa.rpc-identity',pass:c.rpcProbe?.chainId===1&&c.rpcProbe?.blockHash===c.expectedBlockHash&&c.rpcProbe?.identityNormalized===true,failureCode:'MEDUSA_FORK_IDENTITY_MISMATCH',summary:'Medusa fork RPC identity/block differs from frozen campaign state',expected:{chainId:1,blockHash:c.expectedBlockHash,identityNormalized:true},observed:c.rpcProbe??null,remediation:'Use the existing runner-managed normalized Ethereum RPC at the exact frozen block.'}));
 x.push(check({id:'medusa.smoke',pass:TERMINAL.has(c.tinyTargetSmoke?.terminalStatus),failureCode:'MEDUSA_TARGET_SMOKE_NOT_TERMINAL',summary:'Tiny campaign against the actual staged target did not reach normalized terminal evidence',expected:[...TERMINAL],observed:c.tinyTargetSmoke??null,remediation:'Repair tool/harness/parser readiness before starting the full campaign.'}));
 x.push(check({id:'medusa.secret-redaction',pass:c.normalizedEvidenceContainsRpcSecret===false,failureCode:'MEDUSA_SECRET_LEAK_IN_EVIDENCE',summary:'Normalized Medusa evidence contains an RPC secret',expected:false,observed:c.normalizedEvidenceContainsRpcSecret??null,remediation:'Redact the runtime URL/secret before evidence serialization.'}));
 return finalize('medusa',c,x,{repository:c.repository,ref:c.ref,expectedOutputs:c.expectedOutputs,rollback:'terminate tiny smoke and discard workspace'});
}
