import {check,finalize,requireText,requireSha64} from './common-v1.mjs';
export function preflightPublicationV1(c={}){
 const x=[];
 x.push(check({id:'publication.owner',pass:['CurveYield2/Audit-Controller','CurveYield2/Contract-Automation'].includes(c.ownerRepository),failureCode:'PUBLICATION_OWNER_REPOSITORY_INVALID',summary:'Publication responsibility is assigned to the wrong repository',expected:['CurveYield2/Audit-Controller','CurveYield2/Contract-Automation'],observed:c.ownerRepository??null,remediation:'Route private PDF publication through Audit-Controller; generic public technical artifacts through Contract-Automation.'}));
 x.push(requireText('publication.kind',c.publicationKind,{code:'PUBLICATION_KIND_MISSING',summary:'Publication kind is missing',remediation:'Declare PDF/private or generic public artifact publication.'}));
 x.push(check({id:'publication.input-complete',pass:c.inputArtifactsComplete===true,failureCode:'PUBLICATION_INPUT_ARTIFACT_MISSING',summary:'Required report/source/reference artifacts are incomplete',expected:true,observed:c.missingArtifacts??c.inputArtifactsComplete??null,remediation:'Resolve all required source/report/reference artifacts before renderer/upload.'}));
 x.push(requireSha64('publication.input-digest',c.inputBundleDigest,{code:'PUBLICATION_INPUT_BUNDLE_DIGEST_INVALID',summary:'Publication input bundle is not integrity-bound',remediation:'Hash the exact input bundle before rendering/publishing.'}));
 x.push(check({id:'publication.private-data',pass:c.privateDataExposure===false,failureCode:'PUBLICATION_PRIVATE_DATA_EXPOSURE',summary:'Publication path would expose private campaign data or secret material',expected:false,observed:c.privateDataExposure??null,remediation:'Keep private campaign/reference material inside approved private publication boundary.'}));
 x.push(check({id:'publication.secret-redaction',pass:c.secretLeakDetected===false,failureCode:'PUBLICATION_SECRET_LEAK',summary:'Publication preview/output contains secret material',expected:false,observed:c.secretLeakDetected??null,remediation:'Redact/remove secrets and regenerate output before publication.'}));
 x.push(check({id:'publication.preview',pass:c.previewValidation?.status==='PASS',failureCode:'PUBLICATION_PREVIEW_VALIDATION_FAILED',summary:'Generated artifact failed format/resolver/visual/content pre-publication checks',expected:'PASS',observed:c.previewValidation??null,remediation:'Fix the exact preview/resolver/generator diagnostic before upload.'}));
 x.push(check({id:'publication.destination',pass:c.destinationWritable===true&&typeof c.destination==='string'&&c.destination.length>0,failureCode:'PUBLICATION_DESTINATION_NOT_READY',summary:'Publication destination is not resolved/writable',expected:'writable destination',observed:{destination:c.destination??null,writable:c.destinationWritable??null},remediation:'Resolve target folder/path/permissions before publication.'}));
 x.push(check({id:'publication.overwrite',pass:c.destinationExists!==true||c.overwriteIntent===true,failureCode:'PUBLICATION_OVERWRITE_NOT_EXPLICIT',summary:'Destination exists without explicit overwrite/revision intent',expected:true,observed:{destinationExists:c.destinationExists??null,overwriteIntent:c.overwriteIntent??false},remediation:'Publish a new version or explicitly authorize replacement after digest comparison.'}));
 return finalize('publication',c,x,{repository:c.ownerRepository,ref:c.ref,expectedOutputs:[c.destination].filter(Boolean),rollback:c.rollbackPlan});
}
