import {check,finalize,requireText,requireSha40,nonEmptyArrayCheck} from './common-v1.mjs';
const CANONICAL=new Set(['.github/workflows/audit-controller-execution.yml','.github/workflows/v7-execution-infrastructure-qualification.yml']);
export function preflightWorkflowV1(c={}){
 const x=[];
 x.push(requireText('workflow.repository',c.repository,{code:'WORKFLOW_REPOSITORY_MISSING',summary:'Workflow repository identity is missing',remediation:'Set repository to the exact owner/name that will receive the event.'}));
 x.push(requireSha40('workflow.ref',c.ref,{code:'WORKFLOW_REF_NOT_IMMUTABLE',summary:'Workflow preflight requires an exact commit SHA',remediation:'Resolve the candidate ref to its current 40-character commit SHA before triggering.'}));
 x.push(requireText('workflow.path',c.workflowPath,{code:'WORKFLOW_PATH_MISSING',summary:'Workflow path is missing',remediation:'Use the exact active workflow path.'}));
 x.push(check({id:'workflow.canonical',pass:CANONICAL.has(c.workflowPath)||c.classification==='ACTIVE_PREFLIGHT_REQUIRED',failureCode:'WORKFLOW_NONCANONICAL_ENTRYPOINT',summary:'Workflow is not a classified active entrypoint',expected:[...CANONICAL,'or explicit ACTIVE_PREFLIGHT_REQUIRED classification'],observed:{workflowPath:c.workflowPath,classification:c.classification??null},remediation:'Use the canonical workflow or classify this exact workflow in OPERATION_REGISTRY before execution.'}));
 x.push(check({id:'workflow.trigger',pass:c.triggerAllowed===true,failureCode:'WORKFLOW_EVENT_NOT_ADMITTED',summary:'Workflow event/trigger is not admitted for this action',expected:true,observed:c.triggerAllowed??null,remediation:`Verify the '${c.event??'unknown'}' event exists in the workflow and is valid for this ref.`}));
 const req=new Set(c.requiredSecrets??[]), have=new Set(c.availableSecretNames??[]), missing=[...req].filter(s=>!have.has(s));
 x.push(check({id:'workflow.secrets',pass:missing.length===0,failureCode:'WORKFLOW_REQUIRED_SECRET_UNAVAILABLE',summary:'Required GitHub secret is unavailable in this event class',expected:[...req],observed:{available:[...have],missing},remediation:'Use a trusted event/ref where the named secret is available; never substitute a requester-supplied secret.'}));
 const perm=c.requiredPermissions??{}, got=c.observedPermissions??{}; const bad=Object.entries(perm).filter(([k,v])=>got[k]!==v);
 x.push(check({id:'workflow.permissions',pass:bad.length===0,failureCode:'WORKFLOW_TOKEN_PERMISSION_MISMATCH',summary:'GITHUB_TOKEN permissions do not satisfy the workflow action',expected:perm,observed:got,remediation:'Set the minimal required workflow permissions before starting the substantive job.'}));
 x.push(check({id:'workflow.inputs',pass:c.inputSchemaValid===true,failureCode:'WORKFLOW_INPUT_SCHEMA_INVALID',summary:'Workflow inputs do not satisfy the action-specific schema',expected:true,observed:c.inputSchemaValid??null,remediation:'Fix the exact workflow input validation errors before dispatch.'}));
 x.push(nonEmptyArrayCheck('workflow.outputs',c.expectedOutputs,{code:'WORKFLOW_OUTPUT_CONTRACT_MISSING',summary:'Expected workflow artifacts/evidence are not declared',remediation:'Declare exact artifact/evidence outputs used for post-run verification.'}));
 x.push(check({id:'workflow.blocking-gate',pass:c.substantiveJobsBlockedByPreflight===true,failureCode:'WORKFLOW_PREFLIGHT_NOT_BLOCKING',summary:'Substantive workflow work can start without a passing preflight',expected:true,observed:c.substantiveJobsBlockedByPreflight??null,remediation:'Add needs: preflight or place preflight before every substantive same-job step.'}));
 const retry=c.retry??null; const retryOK=!retry||retry.isRetry!==true||(retry.failureClassified===true&&retry.targetedDiagnosticPassed===true&&retry.repairApplied===true);
 x.push(check({id:'workflow.retry',pass:retryOK,failureCode:'WORKFLOW_BLIND_RETRY_FORBIDDEN',summary:'Full workflow retry lacks failure classification, targeted diagnostic, and repair evidence',expected:'classified failure + targeted diagnostic PASS + repair applied',observed:retry,remediation:'Inspect failed job/log/artifact, run the smallest diagnostic, repair, then re-preflight.',historicalSignatureId:'WF-RETRY-001'}));
 return finalize('workflow',c,x,{repository:c.repository,ref:c.ref,expectedOutputs:c.expectedOutputs,rollback:c.rollbackPlan});
}
