#!/usr/bin/env node
import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { runGitHubNativeJobV2 } from './run-job-file-v2.mjs';
import { validateDeepAssuranceRequestWithV26V1 } from './schema-v26.mjs';
import { submitV7Request } from './request-submission-v1.mjs';
import { resolveV7Request } from './request-resolution-v1.mjs';
import { initializePhase6HarnessBundle, validatePhase6HarnessBundle } from './phase6-harness-authoring-v1.mjs';
import { checkRunnerManifestV2, writeRunnerManifestV2 } from './runner-manifest-v2.mjs';
import { verifyV7Toolchain } from './v7-toolchain-v1.mjs';
import { V7_POLICY } from './v7-policy.mjs';

const RUNNER_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
function parseArgs(argv){const out={_:[]};for(let i=0;i<argv.length;i++){const token=argv[i];if(!token.startsWith('--')){out._.push(token);continue;}const key=token.slice(2);if(key.startsWith('no-')){out[key.slice(3)]=false;continue;}const next=argv[i+1];if(next!==undefined&&!next.startsWith('--')){out[key]=next;i++;}else out[key]=true;}return out;}
function sha256(bytes){return createHash('sha256').update(bytes).digest('hex');}
function safeArtifactPart(value){return String(value??'unknown').replace(/[^A-Za-z0-9._-]+/g,'-').slice(0,120);}
async function appendGithubEnv(values){const target=process.env.GITHUB_ENV;if(!target)return;const body=Object.entries(values).map(([key,value])=>`${key}=${String(value)}\n`).join('');await fs.appendFile(target,body);}
async function readRequest(requestPath){if(!requestPath)throw new Error('Missing --request <request.json>');const bytes=await fs.readFile(path.resolve(requestPath));let parsed;try{parsed=JSON.parse(bytes.toString('utf8'));}catch(error){throw new Error(`Request JSON parse failed: ${error.message}`);}return{request:validateDeepAssuranceRequestWithV26V1(parsed),bytes};}
async function resolveCommand(args){const result=await resolveV7Request({mode:args.mode,sourceRoot:args.source,requestPath:typeof args['request-path']==='string'?args['request-path']:null,outputPath:args.output??'.v7-request/request.json'});await appendGithubEnv({V7_REQUEST_ID:result.requestId,V7_PHASE_ID:result.phaseId});process.stdout.write(`${JSON.stringify(result,null,2)}\n`);return 0;}
async function executeCommand(args){
 const requestPath=args.request??'.v7-request/request.json';const {request,bytes:requestBytes}=await readRequest(requestPath);const evidenceRoot=path.resolve(args['evidence-dir']??V7_POLICY.evidence.root,request.requestId);const workspaceRoot=path.resolve(args.workspace??'.audit-work/v7-execution');await fs.rm(evidenceRoot,{recursive:true,force:true});await fs.mkdir(evidenceRoot,{recursive:true});
 const runnerCommit=process.env.GITHUB_SHA??null;const result=await runGitHubNativeJobV2(request,{workspaceRoot,environment:process.env,runnerCommit,runnerRoot:RUNNER_ROOT,requestPath});
 const raw=`${JSON.stringify(result,null,2)}\n`;const rawPath=path.join(evidenceRoot,'raw-result.json');await fs.writeFile(rawPath,raw);const artifactDigest=sha256(Buffer.from(raw));const requestTransportSha256=sha256(requestBytes);
 const evidence={schemaVersion:V7_POLICY.evidence.schemaVersion,requestId:request.requestId,requestDigest:request.requestDigest,requestTransportSha256,processId:request.processId,phaseId:request.phaseId,profileId:request.profileId,source:request.source,runnerImplementation:{repository:process.env.GITHUB_REPOSITORY??'CurveYield2/Contract-Automation',commit:runnerCommit,manifest:'process/RUNNER_MANIFEST.json'},phaseContractDigest:request.configuration?.v26?.phaseContractDigest??null,disposition:result.disposition,blocking:result.blocking,owner:result.owner,nextAction:result.nextAction,retryFrom:result.retryFrom,recoveryCommand:result.recoveryCommand,preflight:result.preflight??null,artifactDigest,deploymentGasEvidence:result.deploymentGasEvidence??null,simulationEvidence:result.simulation??null,analysis:result.analysis??{},analysisComponentFailureCount:result.analysisComponentFailureCount??0,failedStepCount:result.failedStepCount??0,failedSteps:result.failedSteps??[],continuityDisposition:result.continuityDisposition??null,
   sbom:result.sbom??null,liteRetainedExecution:result.liteRetainedExecution??null,phase6CampaignEvidence:result.phase6CampaignEvidence??null,foundryCoverage:result.foundryCoverage??null,simulationLedger:result.simulationLedger??null,liveDeploymentAttestation:result.liveDeploymentAttestation??null,reproduction:result.reproduction??null,authoritativeFinding:false};
 await fs.writeFile(path.join(evidenceRoot,'controller-evidence.json'),`${JSON.stringify(evidence,null,2)}\n`);const summary={requestId:request.requestId,phaseId:request.phaseId,disposition:result.disposition,status:result.status,blocking:result.blocking,nextAction:result.nextAction,evidenceRoot,artifactDigest};await fs.writeFile(path.join(evidenceRoot,'execution-summary.json'),`${JSON.stringify(summary,null,2)}\n`);
 const artifactName=`v7-${safeArtifactPart(request.requestId)}-${safeArtifactPart(request.phaseId)}-${request.requestDigest.slice(0,8)}`;await appendGithubEnv({V7_REQUEST_ID:request.requestId,V7_PHASE_ID:request.phaseId,V7_REQUEST_DIGEST:request.requestDigest,V7_ARTIFACT_NAME:artifactName,V7_EVIDENCE_DIR:evidenceRoot,V7_DISPOSITION:result.disposition});process.stdout.write(`${JSON.stringify({ ...summary, ...(result.error ? { error: result.error } : {}) }, null, 2)}\n`);return result.status==='completed'?0:1;
}
async function submitCommand(args){const result=await submitV7Request({requestPath:args.request,repository:args.repository??'CurveYield2/Contract-Automation',base:args.base??'main',branch:typeof args.branch==='string'?args.branch:null,createPullRequest:args.pr!==false});process.stdout.write(`${JSON.stringify(result,null,2)}\n`);return 0;}
async function harnessInitCommand(args){const result=await initializePhase6HarnessBundle({requestPath:args.request,runnerRoot:RUNNER_ROOT,campaign:args.campaign??'property',type:args.type??'standard',bundleId:typeof args.bundle==='string'?args.bundle:null});process.stdout.write(`${JSON.stringify(result,null,2)}\n`);return 0;}
async function harnessValidateCommand(args){const result=await validatePhase6HarnessBundle({bundleId:args.bundle,runnerRoot:RUNNER_ROOT,requestPath:typeof args.request==='string'?args.request:null});process.stdout.write(`${JSON.stringify(result,null,2)}\n`);return result.status==='READY'?0:1;}
async function manifestCommand(args){if(args.write===true){const destination=await writeRunnerManifestV2({runnerRoot:RUNNER_ROOT});process.stdout.write(`${JSON.stringify({status:'WROTE',destination},null,2)}\n`);return 0;}const result=await checkRunnerManifestV2({runnerRoot:RUNNER_ROOT});process.stdout.write(`${JSON.stringify(result,null,2)}\n`);return result.status==='PASS'?0:1;}
async function toolchainVerifyCommand(){const result=await verifyV7Toolchain();process.stdout.write(`${JSON.stringify(result,null,2)}\n`);return result.status==='PASS'?0:1;}
function help(){return `V7 Contract-Automation CLI\n\nCommands:\n  resolve --mode pr|dispatch --source <checkout> [--request-path campaigns/.../request.json] [--output .v7-request/request.json]\n  execute --request <request.json> [--workspace <dir>] [--evidence-dir <dir>]\n  submit --request <request.json> [--repository owner/repo] [--base main] [--branch name] [--no-pr]\n  harness:init --request <request.json> [--campaign discovery|property|targeted] [--type standard] [--bundle id]\n  harness:validate --bundle <bundle-id> [--request <request.json>]\n  toolchain:verify\n  manifest [--check] [--write]\n`;}
async function main(){const [command,...rest]=process.argv.slice(2);const args=parseArgs(rest);if(!command||command==='help'||command==='--help'){process.stdout.write(help());return 0;}if(command==='resolve')return resolveCommand(args);if(command==='execute')return executeCommand(args);if(command==='submit')return submitCommand(args);if(command==='harness:init')return harnessInitCommand(args);if(command==='harness:validate')return harnessValidateCommand(args);if(command==='toolchain:verify')return toolchainVerifyCommand(args);if(command==='manifest')return manifestCommand(args);throw new Error(`Unknown v7 command: ${command}`);}
main().then(code=>{process.exitCode=code;}).catch(error=>{console.error(JSON.stringify({status:'CLI_FAILURE',message:error?.message??String(error),kind:error?.kind??null},null,2));process.exitCode=1;});
